# -*- coding: utf-8 -*-
"""app.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QhGlJ8s5hjfeGLWQ95VNvUr1icg14Ljf
"""

import streamlit as st
import tempfile
import os
import detection
from detection import process_video

st.set_page_config(page_title="Secutity System", layout="wide")
st.title("Zone Based Detection System")

uploaded_file = st.file_uploader("Choose a video...", type=["mp4", "avi", "mov"])

if uploaded_file is not None:
    #save uploade video in temporary file
    with tempfile.NamedTemporaryFile(delete=False, suffix='.avi') as tem_in:
        tem_in.write(uploaded_file.read())
        temp_file_path = tem_in.name

    #Output video path
    with tempfile.NamedTemporaryFile(delete=False, suffix='.avi') as tem_out:
        output_path = tem_out.name

    with st.spinner("Processing Video..."):
        result_path, total_people,total_intruders, total_snapsort = process_video(temp_file_path, output_path)

    st.success("Video Processed Successfully!")
    #Display 
    col1, col2, col3 = st.columns(3)
    col1.metric("Total People Detection", total_people)
    col2.metric("Total Intruders Detection", total_intruders)
    col3.metric("Snapsort Save", total_snapsort)

    #show process video
    st.video(result_path)

    #Option to downlode process video
    with open(result_path, "rb") as f:
        st.download_button("Download Processed Video", f, file_name="processed_video.mp4")
