# -*- coding: utf-8 -*-
"""demo-security.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1O9Cf00ILMbVR9yxlRRo2AEEsekau9lFy
"""

#import modules
import cv2
import numpy as np
from ultralytics import YOLO
import time

#Lode model
model = YOLO('yolov8n.pt')

#Process Video

def process_video(input_video_path, output_video_path="output.mp4"):
  cap = cv2.VideoCapture(input_video_path)
  #get video propertices for output
  fps = int(cap.get(cv2.CAP_PROP_FPS))
  width = int(cap.get(cv2.CAP_PROP_FRAME_WIDTH))
  height = int(cap.get(cv2.CAP_PROP_FRAME_HEIGHT))

  #Output video writer
  output_video_path = output_video_path.replace('.mp4', '.avi')
  fourcc = cv2.VideoWriter_fourcc(*'XVID')
  out = cv2.VideoWriter(output_video_path, fourcc, fps, (width, height))

  #define restricted zone
  zone = np.array([
      [int(width*0.3), int(height*0.6)],
      [int(width*0.7), int(height*0.6)],
      [int(width*0.7), int(height*0.9)],
      [int(width*0.3), int(height*0.9)]
  ],dtype=np.int32)

  #process each frame
  frame_count = 0
  total_people = 0
  total_intruders = 0
  total_snapsort = 0
  while True:
      ret, frame = cap.read()
      if not ret:
        break
      frame_count += 1

      #run yolo model
      results = model(frame)
      person_boxes = []
      intruder_count = 0
      snapsort_count = 0

      #filter only person
      for box in results[0].boxes:
        if int(box.cls[0].item()) == 0:
          x1,y1,x2,y2 = map(int, box.xyxy[0].tolist())
          conf = box.conf[0].item()
          person_boxes.append((x1,y1,x2,y2,conf))

      #draw bounding box and check zone
      for (x1,y1,x2,y2,conf) in person_boxes:
        test_x = (x1+x2)//2
        test_y = y2
        print(f"test zone: ({test_x},{test_y})")
        print(f"zone : {zone}")
        inside = cv2.pointPolygonTest(zone, (test_x,test_y), False) >= 0
        if inside:
          intruder_count += 1
          snapsort_count += 1
          timestamp = time.strftime("%Y%m%d-%H%M%S")
          filename = f"intruder_{timestamp}_{snapsort_count}.jpg"
          cv2.imwrite(filename, frame)
          print(f"snapsort saved : {filename}")
          color = (0,0,255)
          label = "intruder"
        else:
          color = (0,255,0)
          label = f"peson{conf:.2f}"
        cv2.rectangle(frame, (x1,y1), (x2,y2), color, 2)
        cv2.putText(frame, label, (x1,y1-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5, color, 2)
      total_people += len(person_boxes)
      total_intruders += intruder_count
      total_snapsort += snapsort_count
      #Add counter
      cv2.putText(frame, f"people count: {len(person_boxes)}", (10,30), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,255,0), 2)
      cv2.putText(frame, f"intruder count: {intruder_count}", (10,60), cv2.FONT_HERSHEY_SIMPLEX, 1, (0,0,255), 2)

      #Draw the zone polygon
      cv2.polylines(frame, [zone], True, (0,255,255), 2)
      cv2.putText(frame, "RESTRICTED ZONE",(zone[0][0], zone[0][1]-10), cv2.FONT_HERSHEY_SIMPLEX, 0.5,(0,255,255),1)

      #Write the frame for output video
      out.write(frame)


  cap.release()
  out.release()
  return output_video_path, total_people, total_intruders,total_snapsort